@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@contentType = application/json

### Create Uuser
POST http://{{host}}/create HTTP/1.1
Content-Type: {{contentType}}

 {
    "name" : "Mertie Beier Sr.",
    "lastname" : "Ziemann",
    "age" : 90402,
    "picture" : "http://lorempixel.com/640/480",
    "company" : "Schaefer LLC",
    "email" : "Layne_Kirlin@gmail.com",
    "phone" : "1-666-252-6434 x715",
    "balance" : "934.61",
    "jobTitle" : "Direct Infrastructure Assistant",
    "avatar" : "https://s3.amazonaws.com/uifaces/faces/twitter/coderdiaz/128.jpg",
    "ipv6" : "4e82:20d3:2695:6a75:a5a4:0ad9:bc26:2e35",
    "id" : "cb9d7866-a355-4c6c-9a69-4d8a7d97620b",
    "finance" : {
        "account" : "23856570",
        "accountName" : "Money Market Account"
    },
    "address" : {
        "zipCode" : "35626",
        "city" : "West Elnora",
        "streetAddress" : "968 Emmerich Points",
        "country" : "Czech Republic"
    },
    "shopping" : [ 
        {
            "productName" : "Intelligent Frozen Chips",
            "price" : "664.00",
            "productAdjective" : "Tasty",
            "productMaterial" : "Steel",
            "product" : "Sausages",
            "department" : "Beauty"
        }, 
        {
            "productName" : "Unbranded Cotton Keyboard",
            "price" : "401.00",
            "productAdjective" : "Rustic",
            "productMaterial" : "Soft",
            "product" : "Bacon",
            "department" : "Electronics"
        }, 
        {
            "productName" : "Licensed Concrete Computer",
            "price" : "772.00",
            "productAdjective" : "Sleek",
            "productMaterial" : "Cotton",
            "product" : "Computer",
            "department" : "Beauty"
        }, 
        {
            "productName" : "Fantastic Frozen Cheese",
            "price" : "789.00",
            "productAdjective" : "Handcrafted",
            "productMaterial" : "Plastic",
            "product" : "Fish",
            "department" : "Beauty"
        }, 
        {
            "productName" : "Tasty Frozen Shoes",
            "price" : "422.00",
            "productAdjective" : "Awesome",
            "productMaterial" : "Frozen",
            "product" : "Chicken",
            "department" : "Baby"
        }, 
        {
            "productName" : "Gorgeous Plastic Mouse",
            "price" : "317.00",
            "productAdjective" : "Sleek",
            "productMaterial" : "Wooden",
            "product" : "Salad",
            "department" : "Computers"
        }, 
        {
            "productName" : "Practical Cotton Fish",
            "price" : "174.00",
            "productAdjective" : "Practical",
            "productMaterial" : "Fresh",
            "product" : "Bike",
            "department" : "Books"
        }, 
        {
            "productName" : "Refined Plastic Hat",
            "price" : "170.00",
            "productAdjective" : "Sleek",
            "productMaterial" : "Soft",
            "product" : "Chips",
            "department" : "Music"
        }, 
        {
            "productName" : "Tasty Soft Pizza",
            "price" : "223.00",
            "productAdjective" : "Incredible",
            "productMaterial" : "Cotton",
            "product" : "Mouse",
            "department" : "Movies"
        }
    ],
    "__v" : 0
}
### Get all services
GET  http://localhost:4000/all HTTP/1.1
