

### Create Uuser
POST http://localhost:4000/ HTTP/1.1

{ 
  "name": "Waldo Daniel",
  "lastname": "Schmeler",
  "age": 19436,
  "picture": "http://lorempixel.com/640/480",
  "company": "Borer - Jakubowski",
  "email": "Jules.Casper58@gmail.com",
  "phone": "1-961-579-6644",
  "balance": "795.61" 
}

### Get all services
GET  http://localhost:4000/all HTTP/1.1
