@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@contentType = application/json

### Create Uuser
POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}

{ 
  "name": "Waldo Daniel",
  "lastname": "Schmeler",
  "age": 19436,
  "picture": "http://lorempixel.com/640/480",
  "company": "Borer - Jakubowski",
  "email": "Jules.Casper58@gmail.com",
  "phone": "1-961-579-6644",
  "balance": "795.61" 
}

### Get all services
GET  http://localhost:4000/all HTTP/1.1
